Lab5
ssizova/oop_mmf pull request #8
Opened 2019-04-09 17:14 UTC by ssizova

2019-04-09 17:17 UTC, ssizova commented
Lab is still in process

2019-04-27 12:20 UTC, Dima00782 commented on Task5/InputIterator.h
> +        return rhs.isEnd != this->isEnd;
переиспользуйте operator==

2019-04-27 12:21 UTC, Dima00782 commented on Task5/test/tests.cpp
> +//class CSVParserTests {
закомментареного кода в продакшене быть не должно

2019-04-27 12:24 UTC, Dima00782 commented on Task5/test/tests.cpp
> +CSVParser<int, std::string> p(&f, false, separator, scr);
Глобально объявили?

Надо через fixture: https://github.com/google/googletest/blob/master/googletest/docs/primer.md

2019-04-27 12:25 UTC, Dima00782 commented on Task5/test/tests.cpp
> +    std::ifstream f1("test_file.csv");
Тесты жидковатые.
Мы пишем тесты чтобы реально себе же в будущем помогать, а не просто для формальности.

Давайте добавим реальный тест в котором:
прямо в тесте создадим CSVParser, сделаем стримы из строк
Прочитаем и проверим что все совпадает

2019-04-27 12:27 UTC, Dima00782 commented on Task4/test/md5.h
> +#ifndef TASK4_MD5_H
А это зачем?

2019-04-27 12:27 UTC, dbezhetskov requested changes
В целом хорошо, но есть что доработать

2019-05-03 12:41 UTC, ssizova commented on Task5/test/tests.cpp
> +    std::ifstream f1("test_file.csv");
@Dima00782 ,Это только Integration тест не очень, или в целом?

2019-05-12 10:47 UTC, dbezhetskov approved these changes
Хорошая идея с std::tuple_cat, лабу принимаю

2019-05-12 10:48 UTC, dbezhetskov approved these changes

2019-05-12 10:48 UTC, Dima00782 commented on Task5/test/tests.cpp
> +        EXPECT_EQ(tuples[j],*i);
Да, вот такой тест реально полезен.

2019-05-14 11:47 UTC, merged